# Generated by Django 6.1.1 on 2026-10-02 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='file',
            field=models.FileField(blank=True, default='', null=True, upload_to='profile_pictures'),
        ),
    ]
