# Generated by Django 6.1.1 on 2026-09-29 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='description',
            field=models.TextField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='user',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='profile_pictures'),
        ),
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='tel',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('customer', 'Customer'), ('business', 'Business')], default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='working_hours',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
